pipeline {

    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '5'))
        timeout(time: 5, unit: 'MINUTES')
    }

    agent any

    triggers {
        pollSCM('H/5 * * * *')
    }

    stages {
        stage('Build') {
            agent {
                docker {
                    reuseNode true
                    image 'docker-public.dev.propify.com/openjdk:12-jdk-alpine'
                    args '-v $HOME/.m2:/root/.m2'
                }
            }
            steps {
                sh "./mvnw -B -U -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DskipTests clean package"
            }
            post {
                cleanup {
                    deleteDir()
                }
            }
        }
    }
}
